# Generated by Django 4.1.7 on 2023-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryID',
            field=models.ImageField(default=1, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='category',
            name='categorytypeID',
            field=models.TextField(default=1, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
    ]
